apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: whack-a-pod-admin
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: whack-a-pod-admin
subjects:
- kind: ServiceAccount
  name: whack-a-pod-admin
  namespace: {{ .Release.Namespace }}
