apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: whack-a-pod-admin
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - replicaset
  verbs:
  - delete