---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: admin
---
apiVersion: v1
kind: Service
metadata:
  name: game
  namespace: {{ .Release.Namespace }}
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: game
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api